# Win
# Jobs são executados sumultaneamento, porém com dependencias(needs), um só inicia após o outro ser finalizado.

stages:
  - teste
  - build
  - deploy

executar_teste:
  stage: teste
  before_script:
    -echo "Preparando testes..."
    - chmod +x ./script.sh # +x = permissão de execução
  script:
    - ./script.sh
   # script: ou adicionar o arquivo
   #  - echo "Executando testes..."
   #  - pwd # mostrar o diretório atual
   #  - ls
   #  - cat /etc/os-release # versão da máquina
   #  - mkdir pipeline
   #  - ls
  after_script:
    - echo "Apagando arquivos temporarios..."

executar_teste2:
  stage: teste
  script:
    - echo "Executando teste 2..."

  criar_imagens:
  only:
    - main
  stage: build
  script:
    - echo "Criando as imagens..."

push_imagens:
    only:
    - main
    needs: # só será iniciado quando o criar_imagens for finalizado
      - criar_imagens
    stage: build
      script:
        - echo "Realizando upload das imagens..."

  kubernetes:
    only:
    - main
    stage: deploy
    script:
      - echo "Executando Deploty..."

    
